name    'tompurl-torssh'
version '0.1.0'
source 'https://github.com/tompurl/puppet-torssh'
author 'tompurl'
license 'Apache License, Version 2.0'
summary 'Front SSH with tor'
description 'See summary :-)'
